### ISSUE TITLE
Error installing Network Experience Analytics

### ISSUE THREAD

**Issue by wpsmithtwc** [akamai/cli#51]
Latest version of `akamai`, compiled from source (master branch) using `go build -o akamai`.
```$ akamai install network-experience-analytics
Attempting to fetch command from https://github.com/akamai/cli-network-experience-analytics.git.... 
Attempting to fetch command from https://github.com/akamai/cli-network-experience-analytics.git...... [OK]
Installing.... panic: runtime error: index out of range

goroutine 1 [running]:
main.installPython(0xc42001eb40, 0x44, 0xc4200ae400, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis.smith/Projects/GO/src/github.com/akamai/cli/package_python.go:42 +0x73d
main.installPackageDependencies(0xc42001eb40, 0x44, 0x1562e00, 0x1e)
	/Users/travis.smith/Projects/GO/src/github.com/akamai/cli/command_install.go:129 +0xce1
main.installPackage(0xc420015340, 0x3e, 0x0, 0x0, 0x4)
	/Users/travis.smith/Projects/GO/src/github.com/akamai/cli/command_install.go:99 +0x64d
main.cmdInstall(0xc4200a1080, 0x0, 0xc4200a1080)
	/Users/travis.smith/Projects/GO/src/github.com/akamai/cli/command_install.go:39 +0x145
github.com/urfave/cli.HandleAction(0x14a9500, 0x1574c78, 0xc4200a1080, 0xc420084500, 0x0)
	/Users/travis.smith/Projects/GO/src/github.com/urfave/cli/app.go:490 +0xd2
github.com/urfave/cli.Command.Run(0x15560fa, 0x7, 0x0, 0x0, 0xc42013c370, 0x1, 0x1, 0x0, 0x0, 0x157019d, ...)
	/Users/travis.smith/Projects/GO/src/github.com/urfave/cli/command.go:210 +0xa95
github.com/urfave/cli.(*App).Run(0xc42008f6c0, 0xc4200100f0, 0x3, 0x3, 0x0, 0x0)
	/Users/travis.smith/Projects/GO/src/github.com/urfave/cli/app.go:255 +0x6f8
main.main()
	/Users/travis.smith/Projects/GO/src/github.com/akamai/cli/akamai.go:43 +0xa1```

**Comment by lkowalsk-akamai-com** [comment]
Hi @wpsmithtwc, this issue should be fixed now. Please try with latest release and close the ticket.
