### ISSUE TITLE
issues when uploading large number of certs via CPS 

### ISSUE THREAD

**Issue by davenfonet** [akamai/cli#80]
I've been uploading a number of SNI edge certs via the CLI and get the following error when doing more then 5 or 6 at a time 

Refreshing local cache...
Traceback (most recent call last):
  File "/Users/twhitney1/.akamai-cli/src/cli-cps/bin/akamai-cps", line 25, in <module>
    status = cli()
  File "/Users/twhitney1/.akamai-cli/src/cli-cps/bin/cps.py", line 238, in cli
    return getattr(sys.modules[__name__], args.command.replace("-", "_"))(args)
  File "/Users/twhitney1/.akamai-cli/src/cli-cps/bin/cps.py", line 1419, in create
    setup(args, invoker='create')
  File "/Users/twhitney1/.akamai-cli/src/cli-cps/bin/cps.py", line 424, in setup
    enrollments_json = enrollments_response.json()
  File "/Users/twhitney1/.akamai-cli/src/cli-cps/lib/python/site-packages/requests/models.py", line 877, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 26901 column 5 (char 1899099)

**Comment by lkowalsk-akamai-com** [comment]
Hi, this issue should be raised in cli-cps queue if it is still valid.
