### ISSUE TITLE
`ReferenceError: contractId is not defined` when retrieving a property

### ISSUE THREAD

**Issue by csaxton171** [akamai/cli#98]
&nbsp;  |  &nbsp;
------------ | -------------
platform | macOS catalina 10.15.4
cli version | 1.1.5
property cli version | 1.1.6

## observed behaviour

when attempting to retrieve a property using `akamai property retrieve` the following exception is encountered

```bash

akamai property retrieve <redacted>
... searching propertyName for the-tnl_pipeline-www.uat-thetimes.co.uk
/Users/csaxton/.akamai-cli/src/cli-property/src/website.js:439
                    console.error('... your client credentials have no access to this group, skipping {%s : %s}', contractId, groupId);
                                                                                                                  ^

ReferenceError: contractId is not defined
    at /Users/csaxton/.akamai-cli/src/cli-property/src/website.js:439:115
    at EdgeGrid.<anonymous> (/Users/csaxton/.akamai-cli/src/cli-property/node_modules/edgegrid/src/api.js:91:5)
    at Request.self.callback (/Users/csaxton/.akamai-cli/src/cli-property/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/Users/csaxton/.akamai-cli/src/cli-property/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/Users/csaxton/.akamai-cli/src/cli-property/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
```
#### notes

- the Client API has READ-ONLY access to /papi 
- the cli successfully queries `akamai property list --contract <redacted> --group <redacted>`
- the associated user account can view this target property without issue in Control Center
## expected behaviour

when attempting to retrieve a property that the client has no group rights to access - an error message should be displayed indicating the group id

**Comment by lkowalsk-akamai-com** [comment]
Hi @csaxton171, this issue is against cli-property which is no longer supported. Please check https://github.com/akamai/cli-property-manager instead.
