### ISSUE TITLE
Panic when running `akamai config set`

### ISSUE THREAD

**Issue by adrhumphreys** [akamai/cli#99]
When running the command `akamai config set host a` I get an error:
```
akamai config set host 'a'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1170a06]

goroutine 1 [running]:
github.com/akamai/cli/vendor/github.com/go-ini/ini.(*Key).SetValue(0x0, 0x7ffeefbffa57, 0x1)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/vendor/github.com/go-ini/ini/key.go:744 +0x26
main.setConfigValue(0x7ffeefbffa52, 0x4, 0x0, 0x0, 0x7ffeefbffa57, 0x1)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/config.go:177 +0x95
main.cmdConfigSet(0xc0000d8dc0)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/command_config.go:30 +0xeb
github.com/akamai/cli/vendor/github.com/urfave/cli.HandleAction(0x1571340, 0x1679fe8, 0xc0000d8dc0, 0xc0000caa00, 0x0)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/vendor/github.com/urfave/cli/app.go:492 +0x7c
github.com/akamai/cli/vendor/github.com/urfave/cli.Command.Run(0x1654b72, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/vendor/github.com/urfave/cli/command.go:210 +0x991
github.com/akamai/cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc000172000, 0xc0000d8b00, 0x0, 0x0)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/vendor/github.com/urfave/cli/app.go:379 +0x7fa
github.com/akamai/cli/vendor/github.com/urfave/cli.Command.startApp(0x16557e7, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/vendor/github.com/urfave/cli/command.go:298 +0x817
github.com/akamai/cli/vendor/github.com/urfave/cli.Command.Run(0x16557e7, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/vendor/github.com/urfave/cli/command.go:98 +0x11dc
github.com/akamai/cli/vendor/github.com/urfave/cli.(*App).Run(0xc0000b9d40, 0xc0000d0000, 0x5, 0x5, 0x0, 0x0)
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/vendor/github.com/urfave/cli/app.go:255 +0x6ab
main.main()
	/private/tmp/akamai-20200125-17697-zq8pp4/cli-1.1.5/src/github.com/akamai/cli/akamai.go:46 +0xd9
```

**Comment by lkowalsk-akamai-com** [comment]
Hi @adrhumphreys , this issue should be fixed now. Please try with latest release and close the ticket.
